# Generated by Django 2.2.2 on 2019-07-11 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20190711_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_reply',
            new_name='parent',
        ),
    ]
