# Generated by Django 2.2.2 on 2019-07-12 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20190712_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replycomment',
            old_name='reply',
            new_name='comment',
        ),
    ]
