# Generated by Django 2.2.3 on 2019-07-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_auto_20190712_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='replycomment',
            name='author_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
